# SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

name: eg3d
channels:
  - pytorch
  - nvidia
dependencies:
  - python>=3.9
  - pip
  - numpy>=1.20
  - click
  - pillow
  - scipy
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch::torchvision=0.13.1=py39_cu113
  - requests
  - tqdm
  - ninja
  - matplotlib=3.4.2
  - imageio
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
    - psutil
    - mrcfile
    - tensorboard
    - ipdb
    - pandas
    - spconv
    - https://data.pyg.org/whl/torch-1.12.0%2Bcu113/torch_scatter-2.0.9-cp39-cp39-linux_x86_64.whl
    - ftfy
    - regex
    - dill
    - git+https://github.com/openai/CLIP.git
    - git+https://github.com/mapillary/inplace_abn